# Generated by Django 6.0.8 on 2026-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partner_stores',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
