# Generated by Django 6.0.8 on 2026-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_address_text_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('processing', 'Ishlab chiqarilmoqda'), ('packaging', 'Qadoqlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berilgan'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20),
        ),
    ]
