# Generated by Django 6.0.8 on 2026-08-13 14:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_product_name(apps, schema_editor):
    """Mavjud OrderItem qatorlari uchun product_name'ni joriy product.name'dan
    to'ldiradi — shu tufayli eski buyurtmalar migratsiyadan keyin ham to'liq
    ko'rinishda qoladi (keyinchalik mahsulot o'chirilsa ham)."""
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.select_related('product').exclude(product__isnull=True):
        item.product_name = item.product.name
        item.save(update_fields=['product_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(backfill_product_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
