# Generated by Django 6.0.8 on 2026-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_product_is_featured_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
