# Generated by Django 6.0.8 on 2026-08-13 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_read_by_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "qo'llab-quvvatlash xabari",
                'verbose_name_plural': "qo'llab-quvvatlash xabarlari",
                'ordering': ['created_at'],
            },
        ),
    ]
