# Generated by Django 5.2.15 on 2026-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('staff', 'Xodim'), ('manager', 'Menejer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='customer', max_length=20),
        ),
    ]
