# Generated by Django 6.0.8 on 2026-08-12 14:06

from django.db import migrations, models


def migrate_old_roles_to_staff(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role__in=['customer', 'manager']).update(role='staff')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(migrate_old_roles_to_staff, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Mijoz'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='staff', max_length=20),
        ),
    ]
