# Generated by Django 6.0.8 on 2026-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('staff', 'Mijoz'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='', help_text="Django admin orqali berilgan, lekin foydalanuvchi profilini (ism, familiya, telefon, rasm) to'ldirmaguncha kuchga kirmaydigan rol.", max_length=20),
        ),
    ]
